# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TechBook

  target 'TechBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TechBookUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire'
pod 'SDWebImage'
pod 'DropDown'
end
